version: "3.4"

services:
    pgAdmin:
        restart: always
        image: dpage/pgadmin4
        ports:
            - "8000:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: 1234@admin.com
            PGADMIN_DEFAULT_PASSWORD: 1234
        volumes:
            - pgadmin:/var/lib/pgadmin
    postgres:
        build: ./postgres
        restart: always
        #command: sh -c "postgres -D /usr/local/pgsql/data && psql /sql/car_schema_create.sql && psql /sql/data_insert.sql"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgrespassword123!
            POSTGRES_DB: testdb
        container_name: "postgres_container"
        ports:
            - "5432:5432"
        volumes:
            - pgvol:/var/lib/postgresql/data
volumes:
    pgvol:
    pgadmin: 